### ISSUE TITLE
Typo error in Workshop 5 part 1

### ISSUE THREAD

**Issue by prathamgarg456** [Seneca-144100/IPC-Workshops#3]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93202746/138890268-ae66b612-18bf-4b8b-babe-bf5eb46eb1ec.png)
"There is no space in pdf after comma(,)"
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/93202746/138890545-2ed9aacc-2d9f-4889-b2ca-a2f607bb0045.png)

**Comment by CameronGray1210** [comment]
Thanks for your feedback - this has been updated and pushed to the production repo.

**Comment by CameronGray1210** [comment]
Thanks for your feedback - this has been updated and pushed to the production repo.


Cameron Gray
Faculty, Course Lead (IPC144 && APS145)
Seneca College<http://senecacollege.ca/> – FASET
School of Software Design and Data Science (SDDS<http://sdds.senecacollege.ca/>)

From: prathamgarg456 ***@***.***>
Sent: Tuesday, October 26, 2021 9:40 AM
To: Seneca-144100/IPC-Workshops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Seneca-144100/IPC-Workshops] Typo error in Workshop 5 part 1 (Issue #3)

[EXTERNAL EMAIL] Please take caution when clicking links, opening attachments or responding to requests for information.


[MicrosoftTeams-image]<https://user-images.githubusercontent.com/93202746/138890268-ae66b612-18bf-4b8b-babe-bf5eb46eb1ec.png>
"There is no space in pdf after comma(,)"
[MicrosoftTeams-image (1)]<https://user-images.githubusercontent.com/93202746/138890545-2ed9aacc-2d9f-4889-b2ca-a2f607bb0045.png>
