### ISSUE TITLE
Typo Error in Workshop 5 Part 2

### ISSUE THREAD

**Issue by prathamgarg456** [Seneca-144100/IPC-Workshops#4]
one more error in pdf. In part 2 we have to remove one exclamation mark(!).In pdf there are two exclamation marks (!!), we have to use only one exclamation mark(!). Peace!!
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/93202746/138891085-d93eb6f4-618f-40e8-b291-24fa6af3d5ab.png)

**Comment by CameronGray1210** [comment]
Thanks for your feedback - this has been updated and pushed to the production repo.

**Comment by CameronGray1210** [comment]
Thanks for your feedback - this has been updated and pushed to the production repo.


Cameron Gray
Faculty, Course Lead (IPC144 && APS145)
Seneca College<http://senecacollege.ca/> – FASET
School of Software Design and Data Science (SDDS<http://sdds.senecacollege.ca/>)

From: prathamgarg456 ***@***.***>
Sent: Tuesday, October 26, 2021 9:42 AM
To: Seneca-144100/IPC-Workshops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Seneca-144100/IPC-Workshops] Typo Error in Workshop 5 Part 2 (Issue #4)

[EXTERNAL EMAIL] Please take caution when clicking links, opening attachments or responding to requests for information.


one more error in pdf. In part 2 we have to remove one exclamation mark(!).In pdf there are two exclamation marks (!!), we have to use only one exclamation mark(!). Peace!!
[MicrosoftTeams-image (2)]<https://user-images.githubusercontent.com/93202746/138891085-d93eb6f4-618f-40e8-b291-24fa6af3d5ab.png>
