### ISSUE TITLE
typo in workshop6part2

### ISSUE THREAD

**Issue by prathamgarg456** [Seneca-144100/IPC-Workshops#5]
(only one typo in Workshop6part2 Not a big one ) this bracket ')' is not required , don't print this bracket
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93202746/140553157-e7113eb8-95f1-428f-b9d5-b3e38a8269eb.png)

**Comment by CameronGray1210** [comment]
Thanks – This has been fixed and will be applied for next term (too late now for releasing this).


Cameron Gray
Faculty, Course Lead (IPC144 && APS145)
Seneca College<http://senecacollege.ca/> – FASET
School of Software Design and Data Science (SDDS<http://sdds.senecacollege.ca/>)

From: prathamgarg456 ***@***.***>
Sent: Friday, November 5, 2021 1:28 PM
To: Seneca-144100/IPC-Workshops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Seneca-144100/IPC-Workshops] typo in workshop6part2 (Issue #5)

[EXTERNAL EMAIL] Please take caution when clicking links, opening attachments or responding to requests for information.


(only one typo in Workshop6part2 Not a big one ) this bracket ')' is not required , don't print this bracket
[MicrosoftTeams-image]<https://user-images.githubusercontent.com/93202746/140553157-e7113eb8-95f1-428f-b9d5-b3e38a8269eb.png>
