### ISSUE TITLE
w5p1 max/min year

### ISSUE THREAD

**Issue by cykuotw** [Seneca-144100/IPC-Workshops#7]
Since min/max year are set to be 2012/2022 in the previous instruction.
Maybe the output should be something like "between 2012 and 2022"?
![image](https://user-images.githubusercontent.com/20836152/152037660-ffc60b26-054e-47e9-8fce-136594f77e2c.png)

**Comment by CameronGray1210** [comment]
Thank you... the submitter expects the updates you suggest - the document simply didn't get updated to the new years... this is now fixed and reposted.
