### ISSUE TITLE
Additional .py and .txt files in WS06/p1?

### ISSUE THREAD

**Issue by cykuotw** [Seneca-144100/IPC-Workshops#8]
Hi

I've noticed there are w6p1-auto.py and w6p1-inputs.txt in WS06/p1.
The entire instruction note does not mentioned about anything about .py and .txt files.
Are they put into WS06/p1 by accident?

![image](https://user-images.githubusercontent.com/20836152/152878711-bee66be7-f58c-4d24-bbae-9fdbc9f22140.png)

**Comment by CameronGray1210** [comment]
@cykuotaiwan Please read the workshops 6 "Readme.md", it explains those files.

**Comment by cykuotw** [comment]
my mistake, thank you.
